CREATE DATABASE ELCSA_SED

CREATE TABLE USERS(
UserId INT IDENTITY(1,1) NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL,
ROLEID INT NOT NULL
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
------------
CREATE TABLE Role(
RoleId INT IDENTITY(1,1) NOT NULL,
RoleName VARCHAR(50) NOT NULL
 CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
-------------
CREATE TABLE PERSON(
ID INT IDENTITY(1,1) NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
CELLPHONE1 VARCHAR(10) NOT NULL,
CELLPHONE2 VARCHAR(10) NOT NULL,
EMAILADDRESS VARCHAR(50) NOT NULL,
TITLE VARCHAR(2) NOT NULL,
GENDER VARCHAR(10) NOT NULL,
AGE INT NULL,
PICTURE image NULL,
TYPE VARCHAR(10) NOT NULL,
ROLEID INT NOT NULL,
USERID INT NOT NULL
 CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
----------
CREATE TABLE Announcement(
AnnouncementId int IDENTITY(1,1) NOT NULL,
Heading varchar(100) NOT NULL,
Content varchar(max) NOT NULL,
Date Datetime NOT NULL,
CreatedBy varchar(50) NOT NULL 
)

CREATE TABLE CIRCUIT(
CircuitId INT IDENTITY(1,1) NOT NULL,
NAME VARCHAR(MAX) NOT NULL,
EMAILADDRESS VARCHAR(50) NOT NULL,
CONTACTNUMBER VARCHAR(10) NOT NULL,
PERSONID INT NOT NULL,
ADDRESS VARCHAR(50) NOT NULL
)

CREATE TABLE CIRCUITANNOUNCEMENT(
CircuitId INT NOT NULL,
ANNOUNCEMENTID INT NOT NULL
)

CREATE TABLE SOCIALS(
SOCIALID INT IDENTITY(1,1) NOT NULL,
NAME VARCHAR(MAX) NULL,
URL VARCHAR(MAX) NULL
)
CREATE TABLE CIRCUITSOCIALS(
CIRCUITID INT NOT NULL,
SOCIALID INT NOT NULL
)

CREATE TABLE ADDRESS(
ADDRESSID INT IDENTITY(1,1) NOT NULL,
ADDRESSLINE1 VARCHAR(MAX) NOT NULL,
ADDRESSLINE2 VARCHAR(MAX) NOT NULL,
ADDRESS4LINE3 VARCHAR(MAX) NOT NULL,
SUBURB VARCHAR(50) NULL,
TOWN VARCHAR(50) NULL,
LATITUDE DECIMAL NULL,
LONGITUTDE DECIMAL NULL
)


